parameters:
    form.type.digitalshift_mailbox_message.class: Digitalshift\MailboxFormBundle\Form\Type\MessageType
    form.type.digitalshift_mailbox_message_content.class: Digitalshift\MailboxFormBundle\Form\Type\MessageContentType

services:
    form.type.digitalshift_mailbox_message:
        class: %form.type.digitalshift_mailbox_message.class%
        tags:
            -  { name: form.type, alias: digitalshift_mailbox_message }

    form.type.digitalshift_mailbox_message_content:
            class: %form.type.digitalshift_mailbox_message_content.class%
            arguments: [@digitalshift_mailbox_persistence.attachment_persister]
            tags:
                -  { name: form.type, alias: digitalshift_mailbox_message_content }